general: 
steps:
gctsDeploy:
host: "https://52.191.26.64:8001"
client: "200"
abapCredentialsId: "ADITYA_CREDENTIALS"
repository: "adtygpt-adtygpt"
remoteRepositoryURL: "https://github.com/adtygpt/adtygpt"
role: "SOURCE"
vSID: "DEV"
verbose: true
type: "GIT"
rollback: false
